### ISSUE TITLE
How to use

### ISSUE THREAD

**Issue by lngvietthang** [dnanhkhoa/python-vncorenlp#2]
When I run the code:
`vncorenlp = VnCoreNLP('path/to/VnCoreNLP-1.0.1.jar')`
in python shell, I got this output and this command never end.

![image](https://user-images.githubusercontent.com/4636263/46194098-91fb2c00-c32a-11e8-9dea-703efcf09985.png)

**Comment by lngvietthang** [comment]
I can run it now, but I need to rebuild the VnCoreNLPServer from your source code first.
Could you check VnCoreNLPServer.jar file?
Thank for your contributions!

**Comment by dattx0** [comment]
@lngvietthang how do you rebuild? i cant pull lfs files in VnCoreNLPServer
