### ISSUE TITLE
How to start server 

### ISSUE THREAD

**Issue by manhnguyenquoc** [dnanhkhoa/python-vncorenlp#4]
Hi, 

Thank for this awesome toolkit @dnanhkhoa ,

Could you please show me how to run your toolkit as a service so I can send request to it when using python?

I follow the instruction in [this link](https://github.com/dnanhkhoa/python-vncorenlp#use-an-existing-server) but when I enter the command `vncorenlp -Xmx2g E:\Data\Projects\MobiFone5\NLP\VnCoreNLP-master\VnCoreNLP-1.1.jar -p 9000 -a "wseg,pos,ner,parse"` into command prompt, it returns _'vncorenlp' is not recognized as an internal or external command, operable program or batch file._

How can I run this command properly?

![command prompt](https://user-images.githubusercontent.com/22399058/62760834-33a4eb00-baaf-11e9-850e-f25d08bb23c1.PNG)

**Comment by dnanhkhoa** [comment]
It looks like the system cannot recognize the package vncorenlp, maybe your Python directory is not included in PATH variable. Can you use `python` commmand without any error on your cmd?
