### ISSUE TITLE
corrupted jar

### ISSUE THREAD

**Issue by alg0s** [dnanhkhoa/python-vncorenlp#8]
Hey man, nice work! Just for you to double check the file **_VnCoreNLPServer.jar_** is probably corrupted.

**Comment by dnanhkhoa** [comment]
Hi @alg0s,

Thank you for your message, I have quickly checked with the latest version of VnCoreNLP 1.1.1, there is no problem so far. Could you please check it again or post your problem in detail? Ex. How did you know it's corrupted?

**Comment by dnanhkhoa** [comment]
So I will close this issue, if you still have the problem, please feel free to reopen it. Thanks

**Comment by alg0s** [comment]
Hey, I missed the notification for this. Basically, I download your file and tried to run it and it didn't work. It works when I copied the file you shipped to pypi package. Certainly the file on this repo has issue, not the one with VnCoreNLP python pkg.
